version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  - package-ecosystem: "github-actions"
    directory: "/cuda-binaries/networkbuster.network/packages/usbnb/.github/workflows"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/real-time-overlay"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/cuda-binaries"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/cuda-binaries/api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/cuda-binaries/dashboard"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/cuda-binaries/networkbuster.network"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/cuda-binaries/networkbuster.network/api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/cuda-binaries/networkbuster.network/dashboard"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/cuda-binaries/networkbuster.network/packages/usbnb/New folder/New folder"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/cuda-binaries/networkbuster.network/packages/usbnb/New folder/New folder/api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/cuda-binaries/networkbuster.network/packages/usbnb/New folder/New folder/dashboard"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/cuda-binaries/networkbuster.network/packages/usbnb/New folder/New folder/challengerepo/real-time-overlay"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5